//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDemo.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class cust
    {
        public cust()
        {
            this.saletrans = new HashSet<saletran>();
        }
    
        public int cid { get; set; }
        public string cname { get; set; }
        public string address { get; set; }
    
        public virtual ICollection<saletran> saletrans { get; set; }
    }
}
