//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDemo.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class saletran
    {
        public int stid { get; set; }
        public Nullable<int> pid { get; set; }
        public Nullable<int> rate { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<int> cid { get; set; }
    
        public virtual cust cust { get; set; }
        public virtual product product { get; set; }
    }
}
